# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Eric Johnson
description: Eric Johnson's personal website
baseurl: ""
url: "https://ericjtech.com"
og_image: /assets/img/eric-profile-pic.jpeg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Projects
    - name: Blog
    - name: Resume

footer:
  show_powered_by: true
  contact:
    - type: email
      name: ericjohnson@ericjtech.com
      value: ericjohnson@ericjtech.com
  follow:
    - type: linkedin
      name: LinkedIn
      link: https://www.linkedin.com/in/ejohnson5561/
    - type: github
      name: GitHub
      link: http://github.com/eboi1

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
